---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hostmount-anyuid
  annotations:
    kubernetes.io/description: 'hostmount-anyuid provides all the features of the
      restricted SCC but allows host mounts and any UID by a pod.  This is primarily
      used by the persistent volume recycler. WARNING: this SCC allows host file system
      access as any UID, including UID 0.  Grant with caution.'
spec: 
  privileged: false
  hostIPC: false
  hostPID: false
  hostNetwork: false
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - nfs
  - persistentVolumeClaim
  - projected
  - secret
  fsGroup:
    type: RunAsAny
  readOnlyRootFilesystem: false
  runAsUser:
    type: RunAsAny
  supplementalGroups:
    type: RunAsAny
  requiredDropCapabilities:
  - MKNOD
  seLinuxContext:
    type: MustRunAs

  allowHostDirVolumePlugin: true
  allowPrivilegedContainer: false
  groups: []
  users:
  - system:serviceaccount:openshift-infra:pv-recycler-controller

  allowedCapabilities: null
  allowedFlexVolumes: null
  defaultAddCapabilities: null